host:
  - name: node1
    addr: localhost
    port: 8881
  - name: node2
    addr: localhost
    port: 8882
  - name: node3
    addr: localhost
    port: 8883
  - name: node4
    addr: localhost
    port: 8884