host:
  - name: node0
    addr: localhost
    port: 8880
  - name: node1
    addr: localhost
    port: 8881
  - name: node2
    addr: localhost
    port: 8882
  - name: node3
    addr: localhost
    port: 8883
  - name: node4
    addr: localhost
    port: 8884
client:
  - name: client0
    addr: localhost
    port: 4440
lease:
  master_id: 0
  period: 500
