host:
  - name: node1
    addr: localhost
    port: 8881
  - name: node2
    addr: localhost
    port: 8882
  - name: node3
    addr: localhost
    port: 8883
  - name: node4
    addr: localhost
    port: 8884
  - name: node5
    addr: localhost
    port: 8885
  - name: node6
    addr: localhost
    port: 8886
  - name: node7
    addr: localhost
    port: 8887
  - name: node8
    addr: localhost
    port: 8888