host:
  - name: node0
    addr: 192.168.1.100 
    port: 8880
  - name: node1
    addr: 192.168.1.101 
    port: 8881
  - name: node2
    addr: 192.168.1.102
    port: 8882
client:
  - name: client0
    addr: 192.168.1.103 
    port: 4440
lease:
  master_id: 0
  period: 500
